import { describe, expect, it } from "vitest";
import type { UIMessage } from "ai";
import {
  buildRenderPlan,
  getToolFailureDetail,
  isToolPartFailed,
  type ChatToolPart,
} from "@/client/components/chat/toolParts";
import { humanizeToolLabel } from "@/client/components/chat/ChatMessage";
import { reduceTraceFrame } from "./samTraceReducer";
import type {
  SamToolTraceEvent,
  SamTraceFrame,
} from "@/shared/samToolTraceTypes";

// Regression test (Phase DT / UX Restore):
// Verifies that:
// 1. Normal chat tool activity renders in chronological order, supports ×2 legitimate counts,
//    shows failure state (⚠) with fallback details, and avoids duplicate badges for blocked retries.
// 2. Debug Trace independently captures the full lifecycle (model attempts vs handler executions,
//    blocked retries, provider 402, AI identity, and fallbacks).
// 3. Both layers coexist cleanly and remain available after the final answer.

let seq = 0;
function ev(
  event: SamToolTraceEvent["event"],
  fields: Partial<SamToolTraceEvent> = {},
): SamToolTraceEvent {
  seq += 1;
  return {
    id: `e${seq}`,
    turnId: "turn_coexistence",
    timestamp: Date.now(),
    sequence: seq,
    event,
    ...fields,
  };
}

function toolPart(
  type: `tool-${string}`,
  overrides: Record<string, unknown> = {},
): ChatToolPart {
  return {
    type,
    toolCallId: `call_${seq++}`,
    state: "output-available",
    input: {},
    output: { ok: true },
    ...overrides,
  };
}

describe("SAM Chat Tool Activity and Debug Trace Coexistence", () => {
  it("renders live chat tool activity while Debug Trace independently tracks the full lifecycle", () => {
    // 1. The turn's chat message parts (as generated by AI SDK during streaming & final answer)
    const assistantMessage: UIMessage = {
      id: "msg_sam_turn_1",
      role: "assistant",
      parts: [
        { type: "reasoning", text: "Analyzing organic growth opportunities..." },
        // Legitimate duplicate tool calls:
        toolPart("tool-get_search_console_performance"),
        toolPart("tool-get_search_console_performance"),
        toolPart("tool-list_saved_keywords"),
        toolPart("tool-get_domain_overview"),
        toolPart("tool-get_keyword_metrics"),
        // research_keywords attempt 1: runs, fails with 402 credits unavailable:
        toolPart("tool-research_keywords", {
          output: {
            error:
              'Tool "research_keywords" failed: credits unavailable — it is now unavailable for this turn. Do not retry it in this turn. Use fallback sources instead: Search Console queries, saved keywords, cached keyword data, or SERP analysis.',
            recoveryNotice: "credits unavailable",
          },
        }),
        { type: "reasoning", text: "Attempting keyword research again..." },
        // research_keywords attempt 2: blocked by duplicate-call gate:
        toolPart("tool-research_keywords", {
          output: {
            recoveryBlocked: true,
            error:
              'Tool "research_keywords" is unavailable for this turn because the previous attempt failed with CREDITS_UNAVAILABLE. Do not retry this tool in this turn.',
          },
        }),
        { type: "reasoning", text: "Attempting one more time before fallback..." },
        // research_keywords attempt 3: blocked by duplicate-call gate:
        toolPart("tool-research_keywords", {
          output: {
            recoveryBlocked: true,
            error:
              'Tool "research_keywords" is unavailable for this turn because the previous attempt failed with CREDITS_UNAVAILABLE.',
          },
        }),
        toolPart("tool-get_serp_results"),
        toolPart("tool-save_keywords"),
        toolPart("tool-set_context"),
        {
          type: "text",
          text: "Based on Search Console and SERP data, here are your top organic growth opportunities...",
        },
      ],
    };

    // 2. The turn's sam_trace events broadcast over WebSocket
    const traceEvents: SamToolTraceEvent[] = [
      // get_search_console_performance ×2
      ev("model_attempt", { toolName: "get_search_console_performance" }),
      ev("gate_allowed", { toolName: "get_search_console_performance" }),
      ev("handler_start", { toolName: "get_search_console_performance", attempt: 1 }),
      ev("handler_success", { toolName: "get_search_console_performance", attempt: 1 }),
      ev("tool_completed", { toolName: "get_search_console_performance", attempt: 1 }),

      ev("model_attempt", { toolName: "get_search_console_performance" }),
      ev("gate_allowed", { toolName: "get_search_console_performance" }),
      ev("handler_start", { toolName: "get_search_console_performance", attempt: 1 }),
      ev("handler_success", { toolName: "get_search_console_performance", attempt: 1 }),
      ev("tool_completed", { toolName: "get_search_console_performance", attempt: 1 }),

      // list_saved_keywords
      ev("model_attempt", { toolName: "list_saved_keywords" }),
      ev("gate_allowed", { toolName: "list_saved_keywords" }),
      ev("handler_start", { toolName: "list_saved_keywords", attempt: 1 }),
      ev("handler_success", { toolName: "list_saved_keywords", attempt: 1 }),
      ev("tool_completed", { toolName: "list_saved_keywords", attempt: 1 }),

      // get_domain_overview
      ev("model_attempt", { toolName: "get_domain_overview" }),
      ev("gate_allowed", { toolName: "get_domain_overview" }),
      ev("handler_start", { toolName: "get_domain_overview", attempt: 1 }),
      ev("handler_success", { toolName: "get_domain_overview", attempt: 1 }),
      ev("tool_completed", { toolName: "get_domain_overview", attempt: 1 }),

      // get_keyword_metrics
      ev("model_attempt", { toolName: "get_keyword_metrics" }),
      ev("gate_allowed", { toolName: "get_keyword_metrics" }),
      ev("handler_start", { toolName: "get_keyword_metrics", attempt: 1 }),
      ev("handler_success", { toolName: "get_keyword_metrics", attempt: 1 }),
      ev("tool_completed", { toolName: "get_keyword_metrics", attempt: 1 }),

      // research_keywords: attempt 1 (fails 402)
      ev("model_attempt", { toolName: "research_keywords" }),
      ev("gate_allowed", { toolName: "research_keywords" }),
      ev("handler_start", { toolName: "research_keywords", attempt: 1 }),
      ev("provider_request", { toolName: "research_keywords", provider: "DataForSEO" }),
      ev("provider_error", {
        toolName: "research_keywords",
        provider: "DataForSEO",
        httpStatus: 402,
        errorCode: "CREDITS_UNAVAILABLE",
      }),
      ev("handler_error", {
        toolName: "research_keywords",
        attempt: 1,
        errorCode: "CREDITS_UNAVAILABLE",
        httpStatus: 402,
      }),
      ev("fallback_selected", {
        toolName: "research_keywords",
        fallbackHint: "Search Console queries, saved keywords, cached keyword data, or SERP analysis",
      }),
      ev("tool_completed", {
        toolName: "research_keywords",
        errorCode: "CREDITS_UNAVAILABLE",
      }),

      // research_keywords: attempt 2 (blocked)
      ev("model_attempt", { toolName: "research_keywords" }),
      ev("gate_blocked", { toolName: "research_keywords", blocked: true, errorCode: "CREDITS_UNAVAILABLE" }),
      ev("fallback_selected", {
        toolName: "research_keywords",
        blocked: true,
        fallbackHint: "Search Console queries, saved keywords, cached keyword data, or SERP analysis",
      }),
      ev("tool_completed", { toolName: "research_keywords", blocked: true, errorCode: "CREDITS_UNAVAILABLE" }),

      // research_keywords: attempt 3 (blocked)
      ev("model_attempt", { toolName: "research_keywords" }),
      ev("gate_blocked", { toolName: "research_keywords", blocked: true, errorCode: "CREDITS_UNAVAILABLE" }),
      ev("fallback_selected", {
        toolName: "research_keywords",
        blocked: true,
        fallbackHint: "Search Console queries, saved keywords, cached keyword data, or SERP analysis",
      }),
      ev("tool_completed", { toolName: "research_keywords", blocked: true, errorCode: "CREDITS_UNAVAILABLE" }),

      // get_serp_results
      ev("model_attempt", { toolName: "get_serp_results" }),
      ev("gate_allowed", { toolName: "get_serp_results" }),
      ev("handler_start", { toolName: "get_serp_results", attempt: 1 }),
      ev("handler_success", { toolName: "get_serp_results", attempt: 1 }),
      ev("tool_completed", { toolName: "get_serp_results", attempt: 1 }),

      // save_keywords
      ev("model_attempt", { toolName: "save_keywords" }),
      ev("gate_allowed", { toolName: "save_keywords" }),
      ev("handler_start", { toolName: "save_keywords", attempt: 1 }),
      ev("handler_success", { toolName: "save_keywords", attempt: 1 }),
      ev("tool_completed", { toolName: "save_keywords", attempt: 1 }),

      // set_context
      ev("model_attempt", { toolName: "set_context" }),
      ev("gate_allowed", { toolName: "set_context" }),
      ev("handler_start", { toolName: "set_context", attempt: 1 }),
      ev("handler_success", { toolName: "set_context", attempt: 1 }),
      ev("tool_completed", { toolName: "set_context", attempt: 1 }),
    ];

    const traceFrame: SamTraceFrame = {
      type: "sam_trace",
      events: traceEvents,
      ai: { provider: "Ollama Cloud", model: "kimi-k2.7-code" },
    };

    // ─── VERIFY LAYER A: NORMAL CHAT TOOL ACTIVITY ─────────────────────────
    const plan = buildRenderPlan(assistantMessage.parts);

    const toolEntries = plan.filter(
      (entry): entry is Extract<(typeof plan)[number], { kind: "tools" }> =>
        entry.kind === "tools",
    );

    // Exact user-facing order of tool groups:
    const renderedToolTypes = toolEntries.map((e) => e.group.type);
    expect(renderedToolTypes).toEqual([
      "tool-get_search_console_performance",
      "tool-list_saved_keywords",
      "tool-get_domain_overview",
      "tool-get_keyword_metrics",
      "tool-research_keywords",
      "tool-get_serp_results",
      "tool-save_keywords",
      "tool-set_context",
    ]);

    // Check count on legitimate multiple call:
    const gscEntry = toolEntries[0];
    expect(gscEntry.group.parts).toHaveLength(2);
    expect(humanizeToolLabel(gscEntry.group.type).done).toBe("Get search console performance");

    // Check research_keywords:
    // It must appear ONCE (attempts 2 & 3 were blocked retries and must NOT create duplicate badges or inflate count)
    const rkEntry = toolEntries.find(
      (e) => e.group.type === "tool-research_keywords",
    );
    expect(rkEntry).toBeDefined();
    expect(rkEntry?.group.parts).toHaveLength(1);
    expect(isToolPartFailed(rkEntry!.group.last)).toBe(true);
    expect(getToolFailureDetail(rkEntry!.group.last)).toBe(
      "Credits unavailable — using fallback",
    );

    // Final answer text part is present at the end of the plan:
    const lastPlanEntry = plan[plan.length - 1];
    expect(lastPlanEntry.kind).toBe("part");
    if (lastPlanEntry.kind === "part" && lastPlanEntry.part.type === "text") {
      expect(lastPlanEntry.part.text).toContain(
        "Based on Search Console and SERP data",
      );
    }

    // ─── VERIFY LAYER B: DETAILED DEBUG TRACE ──────────────────────────────
    const traceView = reduceTraceFrame(traceFrame);

    // AI identity:
    expect(traceView.ai.provider).toBe("Ollama Cloud");
    expect(traceView.ai.model).toBe("kimi-k2.7-code");

    // Detailed lifecycle for research_keywords:
    const rkTrace = traceView.tools.find((t) => t.toolName === "research_keywords");
    expect(rkTrace).toBeDefined();
    expect(rkTrace?.modelAttempts).toBe(3);
    expect(rkTrace?.handlerExecutions).toBe(1);
    expect(rkTrace?.providerCalls).toBe(1);
    expect(rkTrace?.blockedRetries).toBe(2);
    expect(rkTrace?.finalOk).toBe(false);
    expect(rkTrace?.lastProviderError?.httpStatus).toBe(402);
    expect(rkTrace?.fallback).toContain("Search Console queries");

    // Summary counts:
    expect(traceView.summary.errors402).toBe(1);
    expect(traceView.summary.blocked).toBe(2);
    expect(traceView.summary.uniqueTools).toBe(8);
  });
});
