import { getDatabaseProvider } from "./provider";
import * as sqliteApp from "./app.schema";
import * as sqliteAudit from "./audit.schema";
import * as sqliteSam from "./sam.schema";
import * as sqliteAuth from "./better-auth-schema";
import * as sqliteBilling from "./billing.schema";
import * as sqliteGsc from "./gsc.schema";
import * as sqliteGa4 from "./ga4.schema";
import * as sqliteIntelligence from "./intelligence.schema";
import * as sqliteInsights from "./insights.schema";
import * as sqliteOpportunities from "./opportunities.schema";
import * as sqliteReports from "./reports.schema";
import * as sqliteReportSharing from "./report-sharing.schema";
import * as sqliteAutopilot from "./autopilot.schema";
import * as sqliteReddit from "./reddit-attribution.schema";
import * as sqliteTelemetry from "./telemetry.schema";
import * as pgApp from "./pg/app.schema";
import * as pgAudit from "./pg/audit.schema";
import * as pgSam from "./pg/sam.schema";
import * as pgAuth from "./pg/better-auth-schema";
import * as pgBilling from "./pg/billing.schema";
import * as pgGsc from "./pg/gsc.schema";
import * as pgGa4 from "./pg/ga4.schema";
import * as pgIntelligence from "./pg/intelligence.schema";
import * as pgInsights from "./pg/insights.schema";
import * as pgOpportunities from "./pg/opportunities.schema";
import * as pgReports from "./pg/reports.schema";
import * as pgReportSharing from "./pg/report-sharing.schema";
import * as pgAutopilot from "./pg/autopilot.schema";
import * as pgReddit from "./pg/reddit-attribution.schema";
import * as pgTelemetry from "./pg/telemetry.schema";

// Canonical schema barrel. Repositories import their tables from here and the
// provider-aware `db` from "@/db", so each repository is written ONCE for both
// backends.
//
// The TYPE identity is the SQLite definitions; the runtime VALUES are whichever
// provider is active. `schema-parity.test.ts` asserts the two dialect schemas
// are structurally interchangeable (same tables/columns/nullability/PKs/unique
// indexes), which is what makes the single cast below sound. The Postgres
// schema is the one structural artifact NOT regenerated by `db:generate`, so the
// parity test is its drift guard.
type AppSchema = typeof sqliteApp &
  typeof sqliteAudit &
  typeof sqliteSam &
  typeof sqliteAuth &
  typeof sqliteBilling &
  typeof sqliteGsc &
  typeof sqliteGa4 &
  typeof sqliteIntelligence &
  typeof sqliteInsights &
  typeof sqliteOpportunities &
  typeof sqliteReports &
  typeof sqliteReportSharing &
  typeof sqliteAutopilot &
  typeof sqliteReddit &
  typeof sqliteTelemetry;

const runtimeSchema =
  getDatabaseProvider() === "postgres"
    ? {
        ...pgApp,
        ...pgAudit,
        ...pgSam,
        ...pgAuth,
        ...pgBilling,
        ...pgGsc,
        ...pgGa4,
        ...pgIntelligence,
        ...pgInsights,
        ...pgOpportunities,
        ...pgReports,
        ...pgReportSharing,
        ...pgAutopilot,
        ...pgReddit,
        ...pgTelemetry,
      }
    : {
        ...sqliteApp,
        ...sqliteAudit,
        ...sqliteSam,
        ...sqliteAuth,
        ...sqliteBilling,
        ...sqliteGsc,
        ...sqliteGa4,
        ...sqliteIntelligence,
        ...sqliteInsights,
        ...sqliteOpportunities,
        ...sqliteReports,
        ...sqliteReportSharing,
        ...sqliteAutopilot,
        ...sqliteReddit,
        ...sqliteTelemetry,
      };

// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- guarded by schema-parity.test.ts
const schema = runtimeSchema as unknown as AppSchema;

export const {
  userOnboardingAnswers,
  projects,
  savedKeywords,
  savedKeywordTags,
  savedKeywordTagAssignments,
  keywordMetrics,
  rankTrackingConfigs,
  rankTrackingKeywords,
  rankCheckRuns,
  rankSnapshots,
  rankProviderCalls,
  organizationActivationState,
  projectActivationState,
  backlinkSnapshots,
  competitorSnapshots,
  domainOverviewSnapshots,
  audits,
  auditPages,
  auditLinks,
  auditIssues,
  auditLighthouseResults,
  samSessions,
  samProjectMemory,
  aiAgentSettings,
  user,
  session,
  account,
  verification,
  organization,
  member,
  invitation,
  billingCustomerStatus,
  gscConnections,
  ga4Connections,
  ga4DailySummary,
  ga4DailyAcquisition,
  ga4DailyLandingPages,
  ga4DailyEvents,
  ga4DailyGeo,
  ga4DailyTechnology,
  ga4SyncCoverage,
  ga4Syncs,
  intelligenceRuns,
  intelligenceRunDetectors,
  dashboardInsights,
  insightUserPreferences,
  opportunities,
  opportunityEvents,
  reports,
  reportShares,
  reportEvents,
  organizationBranding,
  projectClientProfiles,
  autopilotRuns,
  autopilotRunAttempts,
  autopilotSteps,
  gscSearchPerformance,
  gscSearchPerformanceSyncs,
  redditAttributions,
  telemetryState,
  seoProviderSettings,
} = schema;

export const rankTrackingSnapshots = rankSnapshots;
