import { z } from "zod";

const ERROR_CODES = [
  "UNAUTHENTICATED",
  "AUTH_CONFIG_MISSING",
  "PAYMENT_REQUIRED",
  "INSUFFICIENT_CREDITS",
  "FORBIDDEN",
  "NOT_FOUND",
  "AUDIT_CAPACITY_REACHED",
  "AUDIT_PAGE_LIMIT_EXCEEDED",
  "AUDIT_ALREADY_RUNNING",
  "VALIDATION_ERROR",
  "CRAWL_TARGET_BLOCKED",
  "BACKLINKS_BILLING_ISSUE",
  "AI_SEARCH_BILLING_ISSUE",
  "DATAFORSEO_AUTH_FAILED",
  "DATAFORSEO_ACCOUNT_PAUSED",
  "DATAFORSEO_ACCESS_PAUSED",
  "CREDITS_UNAVAILABLE",
  "INSUFFICIENT_FUNDS",
  "RATE_LIMITED",
  "COST_LIMIT_EXCEEDED",
  "TOO_MANY_SIMULTANEOUS_QUERIES",
  "UPSTREAM_UNAVAILABLE",
  "TRANSIENT_UPSTREAM",
  "CONFLICT",
  "INTERNAL_ERROR",
] as const;

export const errorCodeSchema = z.enum(ERROR_CODES);

export type ErrorCode = z.infer<typeof errorCodeSchema>;

const NON_REPORTABLE_ERROR_CODES = new Set<ErrorCode>([
  "UNAUTHENTICATED",
  "NOT_FOUND",
  "PAYMENT_REQUIRED",
  "INSUFFICIENT_CREDITS",
  "INSUFFICIENT_FUNDS",
  "CREDITS_UNAVAILABLE",
  "VALIDATION_ERROR",
  "AUDIT_CAPACITY_REACHED",
  "AUDIT_PAGE_LIMIT_EXCEEDED",
  "AUDIT_ALREADY_RUNNING",
  "DATAFORSEO_ACCOUNT_PAUSED",
  "DATAFORSEO_ACCESS_PAUSED",
  "RATE_LIMITED",
  "COST_LIMIT_EXCEEDED",
  "TOO_MANY_SIMULTANEOUS_QUERIES",
]);

export function isErrorCode(value: string): value is ErrorCode {
  return errorCodeSchema.safeParse(value).success;
}

export function shouldCaptureAppErrorCode(
  code: ErrorCode | null | undefined,
): boolean {
  return code == null || !NON_REPORTABLE_ERROR_CODES.has(code);
}
